"""empty message

Revision ID: bcc06fa3181c
Revises: 
Create Date: 2022-04-27 17:16:46.641038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc06fa3181c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendance_number', sa.Integer(), nullable=True),
    sa.Column('congregation', sa.String(length=128), nullable=True),
    sa.Column('day', sa.String(length=16), nullable=True),
    sa.Column('weekday', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_day'), 'attendance', ['day'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_day'), table_name='attendance')
    op.drop_table('attendance')
    # ### end Alembic commands ###
